# Generated by Django 5.1 on 2024-08-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forgetten_password_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermngt.role'),
        ),
    ]
