# Generated by Django 5.1 on 2024-08-14 18:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0002_alter_user_forgetten_password_token_remove_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(validators=[django.core.validators.RegexValidator(message='enter the number in xxx-xxx-xxxx formate', regex='^[d{3}-\\d{3}-\\d{4}]$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(validators=[django.core.validators.RegexValidator(message='enter the number in xxx-xxx-xxxx formate', regex='^[d{3}-\\d{3}-\\d{4}]$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.BooleanField()),
                ('language', models.CharField(max_length=100)),
                ('month_salary', models.FloatField()),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('account_number', models.IntegerField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermngt.departement')),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
