# Generated by Django 5.1 on 2024-08-14 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0003_application_departement_user_photo_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='enter the number in xxx-xxx-xxxx formate', regex='^[d{3}-\\d{3}-\\d{4}]$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='enter the number in xxx-xxx-xxxx formate', regex='^[d{3}-\\d{3}-\\d{4}]$')]),
        ),
    ]
