# Generated by Django 5.1 on 2024-08-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0004_alter_application_mobile_alter_employee_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='mobile',
        ),
    ]
