# Generated by Django 5.1 on 2024-08-15 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0005_remove_application_mobile_remove_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='enter the number in xxx-xxx-xxxx formate', regex='^[d{3}\\d{3}\\d{4}]$')]),
        ),
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='enter the number in xxx-xxx-xxxx formate', regex='^[d{3}\\d{3}\\d{4}]$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
