# Generated by Django 5.1 on 2024-08-15 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0008_alter_application_mobile_alter_employee_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^d\\d\\d\\d-\\d\\d-\\d\\d\\d\\d$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^d\\d\\d\\d-\\d\\d-\\d\\d\\d\\d$')]),
        ),
    ]
