# Generated by Django 5.1 on 2024-08-16 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0010_alter_application_mobile_alter_employee_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('UNAVIALABLE', 'Unavialable')], max_length=100)),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermngt.employee')),
            ],
        ),
    ]
