# Generated by Django 5.1 on 2024-08-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0011_atttendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atttendance',
            name='employeer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermngt.employee'),
        ),
    ]
