# Generated by Django 5.1 on 2024-08-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0012_alter_atttendance_employeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='atttendance',
            name='manto',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
