# Generated by Django 5.1 on 2024-08-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0013_atttendance_manto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.BooleanField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')]),
        ),
    ]
