# Generated by Django 5.1 on 2024-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0014_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
    ]
