# Generated by Django 5.1 on 2024-08-19 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermngt', '0017_alter_attendance_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermngt.employee'),
        ),
    ]
